// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7ituuiwSzm37v2IY-Xwd4LEd_TFi8TH0',
    appId: '1:450679317964:android:d46a158b9179c4e348e969',
    messagingSenderId: '450679317964',
    projectId: 'toplansin-e4363',
    storageBucket: 'toplansin-e4363.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_BwQ-kf_O7XmEXDWuLRLTaPbGxMXKzkw',
    appId: '1:450679317964:ios:df5f200c530fdbff48e969',
    messagingSenderId: '450679317964',
    projectId: 'toplansin-e4363',
    storageBucket: 'toplansin-e4363.firebasestorage.app',
    androidClientId: '450679317964-2lvhahbpvec7lkj8afaafjesdjlmmmjd.apps.googleusercontent.com',
    iosClientId: '450679317964-5e123pqroj0ocpmnori0r65u62nnv0kg.apps.googleusercontent.com',
    iosBundleId: 'com.toplansin.toplansin',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdwm1oNvZ_9R306ukmd_M2_n7iCudRcQ4',
    appId: '1:450679317964:web:08de0d07bb040cf848e969',
    messagingSenderId: '450679317964',
    projectId: 'toplansin-e4363',
    authDomain: 'toplansin-e4363.firebaseapp.com',
    storageBucket: 'toplansin-e4363.firebasestorage.app',
    measurementId: 'G-CVPG2R0XGB',
  );

}